package infraestrutura;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DBHelper {
	private Connection con = null;

	public ResultSet abrirSQL(String sql) throws SQLException {
		Connection conn = conectar();
		ResultSet resultado = null;

		if (conn != null) {
			Statement stmt = conn.createStatement();
			resultado = stmt.executeQuery(sql);
		}

		return resultado;
	}

	public int executarSQL(String sql) throws SQLException {
		Connection conn = conectar();
		int saida = -1;

		if (conn != null) {
			Statement stmt = conn.createStatement();
			saida = stmt.executeUpdate(sql);
			stmt.close();
		}

		return saida;
	}

	public void desconectar() {
		try {
			con.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		con = null;
	}

	public void fecharResultSet(ResultSet rs) {
		try {
			rs.getStatement().close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private Connection conectar() {
		String className = "org.hsqldb.jdbcDriver"; // path of driver class
		String DB_URL = "jdbc:hsqldb:/home/bd"; // URL of database
		String DB_USER = "SA"; // database user id
		String DB_PASSWD = ""; // database password
		String DB = "LojaVirtualDB"; // database type
		try {
			Class.forName(className).newInstance(); // Load the Driver
			con = DriverManager.getConnection(DB_URL + "/" + DB, DB_USER,
					DB_PASSWD);
		} catch (ClassNotFoundException e) {
			throw new RuntimeException("Driver n�o encontrado: " + className, e);
		} catch (InstantiationException e) {
			throw new RuntimeException("Driver n�o pode ser iniciado: "
					+ className, e);
		} catch (IllegalAccessException e) {
			throw new RuntimeException("Driver n�o pode ser iniciado: "
					+ className, e);
		} catch (SQLException e) {
			throw new RuntimeException("Conex�o n�o pode ser iniciada.", e);
		}
		return con;
	}

	// static void criarTabelaAluno() {
	// try {
	// String sql =
	// "CREATE TABLE ALUNO(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL, NOME VARCHAR(30))";
	// PreparedStatement pst = conexao.prepareStatement(sql);
	// pst.executeUpdate();
	// pst.close();
	// } catch (SQLException e) {
	// // TODO Auto-generated catch block
	// e.printStackTrace();
	// }
	// }
	//
	// static void inserirCategoria() {
	// try {
	// String sql =
	// "INSERT INTO CATEGORIAPRODUTO VALUES (1, 'Eletro-dom�sticos')";
	// PreparedStatement pst = conexao.prepareStatement(sql);
	// pst.executeUpdate();
	// pst.close();
	// } catch (SQLException e) {
	// // TODO Auto-generated catch block
	// e.printStackTrace();
	// }
	// }
	//
	public static void main(String[] args) {
		Connection conn = (new DBHelper()).conectar();
		Statement st;
		try {
			st = conn.createStatement();
			ResultSet rs = st.executeQuery("select nome, login, senha from usuario");
			while(rs.next()){
				System.out.println(rs.getString("nome"));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
	// inserirCategoria();
	// listarFuncionarios();
	// try {
	// conexao.close();
	// } catch (SQLException e) {
	// // TODO Auto-generated catch block
	// e.printStackTrace();
	// }
	// }
	//
	// private static void listarFuncionarios() {
	// try {
	// String sql = "select * from CATEGORIAPRODUTO";
	// PreparedStatement pst = conexao.prepareStatement(sql);
	// ResultSet rs = pst.executeQuery();
	// while(rs.next()) {
	// System.out.println(rs.getString("nome"));
	// }
	// pst.close();
	// } catch (SQLException e) {
	// // TODO Auto-generated catch block
	// e.printStackTrace();
	// }
	// }
}
